### ISSUE TITLE
Next.js - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by pestbarn** [fdaciuk/react-trianglify#23]
It looks like the import throws an error when used in a Next.js project with Typescript.

```javascript
import Trianglify from 'react-trianglify'

const Background = () => {
    return (
        <Trianglify />
    )
}

export default Background
```

**Error:**

```bash
ReferenceError: window is not defined

external%20%22react-trianglify%22 (1:0) @ eval

> 1 | module.exports = require("react-trianglify");
```

**Callstack:**

```bash
index.tsx?8abf:291 Uncaught     at Object.<anonymous> (file:///Users/pestbarn/git/testproject/node_modules/react-trianglify/dist/trianglify.js:1:442)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at eval (webpack-internal:///react-trianglify:1:18)
    at Object.react-trianglify (file:///Users/pestbarn/git/testproject/.next/server/pages/index.js:312:1)
    at __webpack_require__ (file:///Users/pestbarn/git/testproject/.next/server/pages/index.js:29:31)
```

**package.json:**

```json
{
  "name": "testproject",
  "scripts": {
    "dev": "next dev",
    "build": "next build && next export",
    "start": "next start"
  },
  "dependencies": {
    "next": "9.5.5",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@types/node": "^14.11.8",
    "@types/react": "^16.9.52",
    "@types/trianglify": "^1.2.0",
    "react-trianglify": "^2.0.5",
    "trianglify": "^3.0.0",
    "typescript": "^4.0.3"
  }
}
```

**Comment by fdaciuk** [comment]
Hey @pestbarn! Thanks for reporting! I'll work on it :)
